### ISSUE TITLE
Error while using at aws ec2

### ISSUE THREAD

**Issue by SaketJNU** [aaugustin/datedelta#5] opened 2018-03-08 15:41 UTC
Hi,

I was working with **aws ec2 instance** with apache server and flask. I installed **datedelta** by using ``pip install datedelta``. Now, in order to restart the server, it is showing the error as in below image:
![error](https://user-images.githubusercontent.com/20414394/37160010-40199b20-2315-11e8-9074-1ef94da58ee8.jpg)

I have fixed it for my application and will open the PR asap.

Thanks,
Dr. Saket

**Comment by SaketJNU** [comment] 2018-03-08 15:52
A PR is opened as: https://github.com/aaugustin/datedelta/pull/6/files

**Comment by aaugustin** [comment] 2018-03-10 07:07
Duplicate of #2.

**Closed as completed by aaugustin** 2018-03-10 07:07 UTC
